[buildPlans.SthennoMono]
family = "Sthenno Mono"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.SthennoMono.variants.design]
two = "straight-neck-serifed"
three = "flat-top-serifless"
four = "closed-serifless"
seven = "straight-serifed"
zero = "oval-dotted"
capital-m = "flat-bottom-serifless"
capital-q = "vertical-crossing"
capital-w = "straight-flat-top-serifless"
a = "single-storey-serifless"
f = "flat-hook-extended"
g = "single-storey-serifless"
i = "hooky"
r = "compact-serifless"
t = "bent-hook-short-neck2"
w = "straight-flat-top-serifless"
y = "cursive-serifless"
long-s = "flat-hook-tailed"
lower-delta = "flat-top"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
lower-tau = "tailed"
asterisk = "hex-low"
paren = "large-contour"
brace = "curly-flat-boundary"
guillemet = "straight"
ampersand = "flat-top"
at = "compact"
percent = "rings-continuous-slash"
question = "corner"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

  [buildPlans.SthennoMono.ligations]
  inherits = "dlig"

[buildPlans.SthennoMono.weights.Thin]
shape = 100
menu = 100
css = 100

[buildPlans.SthennoMono.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.SthennoMono.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.SthennoMono.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.SthennoMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
