[buildPlans.SthennoMono]
family = "Sthenno Mono"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.SthennoMono.variants.design]
digit-form = 'old-style'
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-m = "flat-bottom-serifless"
capital-q = "vertical-crossing"
capital-w = "straight-flat-top-serifless"
a = "single-storey-serifless"
f = "flat-hook-extended-crossbar-at-x-height"
i = "hooky"
j = "flat-hook-serifed"
l = "hooky"
r = "hookless-serifless"
t = "bent-hook-short-neck2"
u = "toothless-rounded-serifless"
w = "straight-asymmetric-serifless"
y = "cursive-serifless"
long-s = "flat-hook-descending"
lower-delta = "flat-top"
lower-mu = "toothless-rounded-serifless"
lower-pi = "tailless"
lower-tau = "tailed"
zero = "diamond-unslashed"
two = "straight-neck-serifed"
three = "flat-top-serifless"
four = "closed-serifless"
five = "upright-arched-serifed"
seven = "straight-serifed"
punctuation-dot = "square"
braille-dot = "square"
asterisk = "hex-low"
paren = "large-contour"
brace = "curly-flat-boundary"
guillemet = "straight"
ampersand = "flat-top"
at = "compact"
percent = "rings-continuous-slash"
question = "corner"
micro-sign = "toothless-rounded-serifless"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

  [buildPlans.SthennoMono.ligations]
  inherits = "dlig"

[buildPlans.SthennoMono.weights.Thin]
shape = 100
menu = 100
css = 100

[buildPlans.SthennoMono.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.SthennoMono.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.SthennoMono.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.SthennoMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
