[buildPlans.Signoir]
family = "Signoir"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Signoir.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "flat-hook-serifed"
capital-m = "flat-bottom-serifless"
capital-q = "vertical-crossing"
capital-r = "straight-open-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-serifless"
f = "flat-hook-extended"
i = "hooky"
j = "flat-hook-serifed"
r = "corner-hooked-serifless"
t = "bent-hook-short-neck2"
w = "straight-flat-top-serifless"
y = "cursive-serifless"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
zero = "oval-dotted"
asterisk = "hex-low"
paren = "large-contour"
brace = "curly-flat-boundary"
at = "compact"
percent = "rings-continuous-slash"
question = "corner"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

  [buildPlans.Signoir.ligations]
  inherits = "dlig"

[buildPlans.Signoir.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Signoir.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Signoir.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
