[buildPlans.SthennoMono]
family = "Sthenno Mono"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.SthennoMono.variants.design]
capital-b = "more-asymmetric-serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-m = "flat-bottom-serifless"
capital-q = "vertical-crossing"
capital-r = "straight-open-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-serifless"
f = "flat-hook-extended"
i = "hooky"
j = "flat-hook-serifed"
l = "hooky"
r = "corner-hooked-serifless"
t = "bent-hook-short-neck2"
w = "straight-flat-top-serifless"
y = "cursive-serifless"
long-s = "flat-hook-tailed"
lower-delta = "flat-top"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
zero = "oval-dotted"
one = "base"
two = "straight-neck-serifed"
three = "flat-top-serifless"
four = "closed-serifless"
seven = "straight-serifed"
tittle = "square"
diacritic-dot = "square"
punctuation-dot = "square"
asterisk = "hex-low"
brace = "curly-flat-boundary"
ampersand = "flat-top"
at = "compact"
percent = "rings-continuous-slash"
question = "corner"
lig-ltgteq = "slanted"
lig-neq = "vertical"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.SthennoMono.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.SthennoMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
